---

- name: Establish subscription status
  shell: >
    subscription-manager status | grep -i overall | cut -d ':' -f2 | xargs
  register: subscription_status

- name: Ensure the system is registered with a Red Hat subscription using an activation key
  redhat_subscription:
    state: present
    org_id: "{{ rhel_org_id }}"
    activationkey: "{{ rhel_activation_key }}"
    force_register: "{{ 'yes' if subscription_status.stdout != 'Current' else 'no' }}"
  when: rhel_activation_key != ""

- name: Ensure the system is registered with a Red Hat subscription using a poolid
  redhat_subscription:
    state: present
    username: "{{ rhel_username }}"
    password: "{{ rhel_password }}"
    pool_ids: "{{ rhel_pool_id }}"
    force_register: "{{ 'yes' if subscription_status.stdout != 'Current' else 'no' }}"
  when: rhel_pool_id != ""

- name: Ensure all necessary RHEL7 repositories are enabled for this system
  command: >
    subscription-manager repos
    --enable=rhel-7-server-rpms
    --enable=rhel-7-server-optional-rpms
    --enable=rhel-7-server-supplementary-rpms
    --enable=rhel-7-server-extras-rpms

- name: Insert exclude list in yum.conf file
  lineinfile:
    path: /etc/yum.conf
    insertafter: '^installonly_limit='
    regexp: 'exclude=.*'
    line: "exclude={{ exclude_list }}"
    state: "{{ include_exclude }}"
  when: ansible_domain == "library.ucla.edu"
